version: "3"
###
# Start development server by running the following command:
#
#   %> docker compose up -d
#
# To open a bash shell into the container, run:
#
#   %> docker compose exec jekyll-sandbox bash
#
###
services:
  jekyll-sandbox:
    image: jekyll/jekyll:builder
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    ports:
      - 4100:4100
    command:
      - sh
      - -c
      - |
        bundle config set --local path 'vendor/bundle'
        bundle install
        bundle exec jekyll serve -P 4100 --verbose --host 0.0.0.0 --watch
    stdin_open: true
    tty: true
