name: Build

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build Site
        run: |
          echo "patch: $GITHUB_RUN_NUMBER" >> _data/version.yml
          echo "sha: $(git rev-parse --short HEAD)" >> _data/version.yml
          bundle exec jekyll build
      - name: Archive site as artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site
      - name: Archive s3_website.yml as artifact
        uses: actions/upload-artifact@v1
        with:
          name: s3_website
          path: s3_website.yml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        uses: ./.github/actions/env

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET_TEST }}
      CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID_TEST }}
    steps:
      - name: Retrieve site from artifacts
        uses: actions/download-artifact@v1
        with:
          name: _site
      - name: Retrieve s3_website.yml from artifacts
        uses: actions/download-artifact@v1
        with:
          name: s3_website
      - name: Move s3_website.yml into root
        run: |
          mv s3_website/s3_website.yml s3_website.yml
      - name: Show values
        run: |
          echo "github.run_id = ${{ github.run_id }}"
          echo "github.run_number = ${{ github.run_number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.sha = ${{ github.sha }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
      - name: Set to production environment values when branch is gh-pages
        if: contains(github.ref, 'gh-pages') || contains(github.head_ref, 'Conditional-or')
        run: |
          echo "::set-env name=S3_BUCKET::${{ secrets.S3_BUCKET }}"
          echo "::set-env name=CLOUDFRONT_ID::${{ secrets.CLOUDFRONT_ID }}"
      - name: S3 Publish
        uses: docker://justinharringa/s3_website:master
        with:
          args: 'push --site _site'


