name: Build

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          bundle package
      - name: Archive site as artifact
        uses: actions/upload-artifact@v1
        with:
          name: vendor
          path: vendor
      - name: Build Site
        run: bundle exec jekyll build
      - name: Archive site as artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Retrieve vendor/ from artifacts
        uses: actions/download-artifact@v1
        with:
          name: vendor
      - name: Retrieve site from artifacts
        uses: actions/download-artifact@v1
        with:
          name: _site
      - name: Test S3 Publish
        run: |
          bundle exec s3_website install
          bundle exec s3_website push --dry-run

