name: Build

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build Site
        run: |
          echo "patch: $GITHUB_RUN_NUMBER" >> _data/version.yml
          echo "sha: $(git rev-parse --short HEAD)" >> _data/version.yml
          bundle exec jekyll build
      - name: Archive site as artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site
      - name: Archive s3_website.yml as artifact
        uses: actions/upload-artifact@v1
        with:
          name: s3_website
          path: s3_website.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    steps:
      - name: Retrieve site from artifacts
        uses: actions/download-artifact@v1
        with:
          name: _site
      - name: Retrieve s3_website.yml from artifacts
        uses: actions/download-artifact@v1
        with:
          name: s3_website
      - name: Show files
        run: |
          find . -type f
          mv s3_website/s3_website.yml s3_website.yml

      - name: Set bucket when not `gh-pages`
        if: {{ !contains(github.ref, "release") }}
        run: print("::set-env name=S3_BUCKET::{}".format( ${{ secrets.S3_BUCKET_TEST }} ))

      - name: S3 Publish
        uses: docker://justinharringa/s3_website:master
        with:
          args: 'push --site _site'


