name: Build

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build Site
        run: bundle exec jekyll build
      - name: Archive site as artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site
